### ISSUE TITLE
Question about the units of the input dataset

### ISSUE THREAD

**Issue by lingchengli** [sbegueria/SPEIbase#2]
Dear sbegueria,

I have a question: Should the inputs (PRE and PET) have the same units?

Recently, I am using your SPEI R code to calculate SPEI. To reproduce the SPEI calculation, I download the CRU PRE and PET datasets. And they have different units, i.e. the PRE with a unit of mm/month while the PET with the unit of mm/day. As you suggested, we can directly use the downloaded datasets as inputs (if I understand right). So during the calculation, the R code will transfer them into the same unit, right? (mm/month or mm/day?).

Or I should transfer them to the same units.

Thanks,

**Comment by AlvaroAvila360** [comment]
Dear Begueria, 
I have the same doubt (PET is in mm/day or I need to convert in mm/month), what is the correct process?
Thanks,
Álvaro

**Comment by Yinshao-lzu** [comment]
> Dear sbegueria,
> 
> I have a question: Should the inputs (PRE and PET) have the same units?
> 
> Recently, I am using your SPEI R code to calculate SPEI. To reproduce the SPEI calculation, I download the CRU PRE and PET datasets. And they have different units, i.e. the PRE with a unit of mm/month while the PET with the unit of mm/day. As you suggested, we can directly use the downloaded datasets as inputs (if I understand right). So during the calculation, the R code will transfer them into the same unit, right? (mm/month or mm/day?).
> 
> Or I should transfer them to the same units.
> 
> Thanks,

Hello，did you solve this problem (mm/day and mm/month)?

**Comment by sbegueria** [comment]
Could you please post this question in the [SPEI](https://github.com/sbegueria/SPEI) repository?
