### ISSUE TITLE
Question about inMask

### ISSUE THREAD

**Issue by liming489** [sbegueria/SPEIbase#3]
Now I am want to focus one country region (I have the shapefile) to do compute the SPEI using the CRU TS dataset.statistic  So now I tried:
    First to turn the shapefile into nc file using ARCGIS. 
    Second, I set inMask='./inputData/mask.nc',
But I got errors:
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: mask"
[1] "file name: ./inputData/mask.nc"
Error in vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE) : 
  Variable not found.
Can you help me? Thanks a lot!

**Comment by sbegueria** [comment]
That’s too much case-specific, sorry, I cannot help.
