### ISSUE TITLE
Error in executing computeSPEI.R

### ISSUE THREAD

**Issue by ghost** [sbegueria/SPEIbase#4]
Hello!

Thanks a lot for providing the R code to compute SPEI!

When I run the R files, I get this message: 

`Error in R_nc4_create: Permission denied (creation mode was 4096)
 Show Traceback
 
 Rerun with Debug
 Error in nc_create(outFile, out.nc.var) : Error in nc_create! `

Do you by chance know what's happening?

Thanks a lot!
Anastasia

**Comment by drewpeltier** [comment]
I have the same issue. I am trying to calculate SPEI for the CRU 4.0.1 dataset.

Did you figure this out by chance?

Thanks,

Drew

edit: it's because I didn't delete the output file created in a previous (ill-fated) run of the function.

**Comment by n-j-p** [comment]
From my experience, this error occurs when the output filepath is not provided correctly.

**Comment by sbegueria** [comment]
Yes, either the output path is wrong or the file exists already.
