### ISSUE TITLE
To calculation at different time scale problem

### ISSUE THREAD

**Issue by musussi** [sbegueria/SPEIbase#5]
Hi sbequeria;
Thank you for open-sharing with community in R program.

When I try to run code, I can get for a 1-month time scale that I can't see any difficulties. I can also see their z-value in the .nc file. But when I look at other different time scales (3-,6-,9- and 12-month), I can't get any result even it runs perfectly. 

if you help me about this issue, it will be great.

Thank for replying...

**Comment by sbegueria** [comment]
Hi Musussi, what is exactly the problem you are seeing?

Santiago Beguería

**Comment by musussi** [comment]
Hi sbequeria;
Thank you for your interest.
I just have solved my problems that is not related to codes, but it was related to understanding output nc. files. When ı want to figure out for a 3-month time scale, it doesn't calculate for first two months due to SPEI 3 month description. I have seen results after 2 months.  

Thank you again for your kindly sharing codes.

**Comment by sbegueria** [comment]
Exactly, the first N-1 time steps have NA values when you compute tne N-scale SPEI.
