### ISSUE TITLE
points of interest

### ISSUE THREAD

**Issue by biancaglez** [sbegueria/SPEIbase#6]
Hello, Santiago @sbegueria 

If I have 69 [points of interest ](https://github.com/forestgeo/Site-Data/blob/master/ForestGEO_site_data.csv)

and I would like to find SPEI data for these locations with the entire CRU version 4 (latest release) time series range.

Where in your script would I customize to generate SPEI for specific lat longs? This may be something worth adding to your README. From looking at your script briefly this location might be the place [to start](https://github.com/sbegueria/SPEIbase/blob/00dafe3a773aaaa3dfce0920f9cf298905dbb300/R/functions.R#L61)

Thank you!

**Comment by sbegueria** [comment]
Hi Bianca,

My script is aimed at generating a gridded SPEI dataset. If you’re interested in single points, it is way more efficient to just use the spei() function in the R package of the same name. Alternatively, you could just use our website (https://spei.csic.es/spei_database/) and extract the time series for those points given their coordinates.

Cheers,



Santiago Beguería 

Estación Experimental de Aula Dei (EEAD-CSIC)
Consejo Superior de Investigaciones Científicas
Avda. Montañana 1005, 50059 - Zaragoza, Spain

+34 976 71 61 58 <tel:+34%20976%2071%2061%2058>
santiago.begueria@csic.es <mailto:santiago.begueria@csic.es>

http://www.eead.csic.es/home/staffinfo?Id=114 <http://www.eead.csic.es/home/staffinfo?Id=114>
https://lcsc.csic.es <https://lcsc.csic.es/>
https://scholar.google.es/citations?user=QEL8DQoAAAAJ&hl=en <https://scholar.google.es/citations?user=QEL8DQoAAAAJ&hl=en>

**Comment by biancaglez** [comment]
Hi @sbegueria  --- I am using the SPEI function for multiple points of interest ..however one site has NA data for the beginning of the date range (the rest of the sites have this data for the specified date range) -- the function doesn't accept NA values for this site... I am replacing these with 0, computing SPEI, and then making these values 0 after the fact (timescale parameter is 1) ... 

Is there a better way to get around this? Or could your function be updated to allow for NA values?
