### ISSUE TITLE
Difference between V2.6 and results based on CRU4.03

### ISSUE THREAD

**Issue by Hyp-meteorolgist** [sbegueria/SPEIbase#7]
Hi sbequeria;
Thank you for open-sharing with community in R program.

When I calculate SPEI based on the CRU4.03 dataset. The results are different from the version 2.6 from https://spei.csic.es/spei_database. Does calculator version 2.5.1 apply to CRU4.03?

Thank for replying...

**Comment by sbegueria** [comment]
There have been some changes in the SPEI package that translate to minor differences in the results. This might be the cause. In any case, you should use version 2.6 of this code with CRU4.03 to replicate the SPEIbase version 2.6.
