### ISSUE TITLE
SPEI for panel data

### ISSUE THREAD

**Issue by alessiolombini** [sbegueria/SPEIbase#9]
Dear Sbegueria,

Thanks a lot for providing the R code to compute SPEI!

I have a question, is there an adaption to the code to run it also for panel data instead of time series? 

Thank you in advance for your time!

**Comment by sbegueria** [comment]
I don't understand, could you provide an example?

**Comment by sbegueria** [comment]
I assume you refer to 3D (spatio-temporal) data blocks. This has been implemented in the SPEI package, so I close the issue.
